### ISSUE TITLE
DCFEB optical links cannot setup automatically at firmware reload after CCB hard reset

### ISSUE THREAD

**Issue by wsicheng** [odmb/odmb7_port_testing#11]
The problem starts happening after merging the pull request #9, that after a firmware reload triggered by the CCB hard reset, the DCFEB links are not guaranteed to be in the good state until a dedicated optical reset is issued through VME command `W 3008 1`.
The last version that these optical links works correctly (always get aligned properly after firmware reload) is the tag `daq-v15.3` ([36e492e](https://github.com/odmb/odmb7_port_testing/commit/36e492e21d1cc6a4873f23b55b0b99db6e8a4602)). And it is also discovered recently that at tag [gbt-v22.1](https://github.com/odmb/odmb7_port_testing/commit/e163ede050cde318c9568f38679417bc6b396bd9) this DCFEB link problem also present, so this is not likely a problem brought by the addition of ODMB5 compatibility.

Hypothesis were made that the power-on reset `pon_reset` signal was not working correctly but it was found not to be the case. An additional `clkwiz_locked` signal is added to the prerequisite of `pon_reset` being released but still it didn't help.

Currently, the temporary solution is issue the optical reset explicitly after the CCB hard reset during the configuration phase of the Test27 (cosmic run) setup. But this cannot be a final solution as in the physics runs there're CCB hard reset issued on a regular basis from the TCDS system, and the ODMB should be up running as soon as possible on its own.

**Comment by psiddire** [comment]
Implemented the fix for the DCFEB optical link initialization issue. The current implementation is based on a counter which customizable instead of using DCFEB DONE signals.
